In [5]:
import pandas as pd 
import numpy as np

In [6]:
df = pd.read_table('sim_data.txt', sep=' ')
X = df.iloc[:,:-1]
y = df.iloc[:,-1]

In [7]:
from ising_covariates import IsingModel

In [12]:
ising_model = IsingModel(n_jobs=-1)
ising_model.fit(X, y, criterion="max")

INFO: Fitting Ising model...
Training variables:   0%|          | 0/5 [00:00<?, ?it/s]/home/igirela/ising-covariates/.venv/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1780: FutureWarning: The default value for l1_ratios will change from None to (0.0,) in version 1.10. From version 1.10 onwards, only array-like with values in [0, 1] will be allowed, None will be forbidden. To avoid this warning, explicitly set a value, e.g. l1_ratios=(0,).
  warnings.warn(
/home/igirela/ising-covariates/.venv/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1811: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratios' instead. Use l1_ratios=(0,) instead of penalty='l2'  and l1_ratios=(1,) instead of penalty='l1'.
  warnings.warn(
/home/igirela/ising-covariates/.venv/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1823: FutureWarning: The fitted a

In [13]:
ising_model._coefs

{'J_0': array([[ 0.        , -1.79817523, -2.05252013, -4.08004514, -1.80267942],
        [-1.79817523,  0.        , -1.84235499, -3.22355593, -2.03398856],
        [-2.05252013, -1.84235499,  0.        , -2.14837086, -2.15147642],
        [-4.08004514, -3.22355593, -2.14837086,  0.        , -4.39210794],
        [-1.80267942, -2.03398856, -2.15147642, -4.39210794,  0.        ]]),
 'h_0': array([[-0.63599427],
        [-1.4564471 ],
        [-2.42214316],
        [-1.06349766],
        [-0.22955018]]),
 'J_y': array([[0.        , 0.        , 0.        , 1.82379841, 0.04956923],
        [0.        , 0.        , 0.        , 1.3790569 , 0.        ],
        [0.        , 0.        , 0.        , 0.13559774, 0.        ],
        [1.82379841, 1.3790569 , 0.13559774, 0.        , 2.37466381],
        [0.04956923, 0.        , 0.        , 2.37466381, 0.        ]]),
 'h_y': array([[4.10622098],
        [4.55516644],
        [4.86012066],
        [4.96927689],
        [0.45099513]])}

In [24]:
Jy = ising_model._coefs['J_y']
hy = ising_model._coefs['h_y']

In [15]:
Jy

array([[0.        , 0.        , 0.        , 1.82379841, 0.04956923],
       [0.        , 0.        , 0.        , 1.3790569 , 0.        ],
       [0.        , 0.        , 0.        , 0.13559774, 0.        ],
       [1.82379841, 1.3790569 , 0.13559774, 0.        , 2.37466381],
       [0.04956923, 0.        , 0.        , 2.37466381, 0.        ]])

In [ ]:
hy

array([[4.10622098],
       [4.55516644],
       [4.86012066],
       [4.96927689],
       [0.45099513]])

In [22]:
rows, cols = np.tril_indices_from(Jy, k=-1)

In [23]:
Jy[rows, cols]

array([0.        , 0.        , 0.        , 1.82379841, 1.3790569 ,
       0.13559774, 0.04956923, 0.        , 0.        , 2.37466381])

In [37]:
np.einsum('ij,jk-> i', X, hy)

array([0.        , 0.        , 8.66138742, ..., 9.07549786, 9.11238255,
       0.45099513], shape=(5000,))

In [38]:
0.5 * np.einsum('ij,jk,ik-> i', X, Jy, X)

array([0.        , 0.        , 0.        , ..., 1.82379841, 0.04956923,
       0.        ], shape=(5000,))

In [39]:
np.einsum('ij,jk-> i', X, hy) + 0.5 * np.einsum('ij,jk,ik-> i', X, Jy, X)

array([ 0.        ,  0.        ,  8.66138742, ..., 10.89929627,
        9.16195178,  0.45099513], shape=(5000,))

In [40]:
hy.shape

(5, 1)